#This file is for illustrative and dev purposes
version: '3'
services:
    web:
        container_name: web
        restart: always
        build: ./altuntas
        command: ./run_web.sh
        env_file:
            - .env
        ports:
            - "8000:8000"
        depends_on:
            - db
    db:
        restart: always
        container_name: db
        image: postgres:9.4
        env_file:
            - .env
        volumes:
            - ./db:/var/lib/postgresql/data/
        # ports:
        #     - '${POSTGRES_DB_PORT}:5432'
    rabbitmq:
        image: rabbitmq:3.8.2-management
        container_name: rabbitmq
        volumes:
            - ./rabbitmq:/etc/rabbitmq/:rw
            - ./rabbitmq:/var/lib/rabbitmq/:rw
            - ./rabbitmq:/var/log/rabbitmq/:rw
        env_file:
            - .env
        # ports:
        #     - "$RABBITMQ_PORT:5672"   
        #     - "$RABBITMQ_MGMT_PORT:15672"
    worker:
        build: ./altuntas
        container_name: worker
        command: ./run_celery_worker.sh
        working_dir: /app
        volumes:
            - ./worker:/app
        env_file:
            - .env
        depends_on:
            - db
            - rabbitmq
            - web
    scheduler:
        build: ./altuntas
        container_name: scheduler
        command: ./run_celery_beat_worker.sh
        working_dir: /app
        volumes:
            - ./scheduler:/app
        env_file:
            - .env
        depends_on:
            - db
            - rabbitmq
            - web
    monitoring:
        build: ./altuntas
        container_name: monitoring
        env_file:
            - .env
        command: ./run_flower.sh
        ports:
            - 8888:8888
        depends_on:
            - db
            - rabbitmq
            - web
